version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:0080"
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/uaissistant
      - poetry_cache:/root/.cache/pypoetry
    command: >
      sh -c "poetry install
             && uvicorn assistant.main:app --host 0.0.0.0 --port 80 --reload"

volumes:
  poetry_cache:
